version: "3.7"

services:
  e_form:
    container_name: e_form
    image: pensiero/apache-php-mysql:php7.4
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    # command: composer update
    deploy:
      replicas: 1
    ports:
      - "8003:80"
    restart: always
    volumes:
      - .:/var/www/html/
